name       : kaccounts-integration
version    : 18.08.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kaccounts-integration-18.08.3.tar.xz : 579bc40c0adb7eea27389a55f93e84f21fa837a6bc4fd6951d58d8d396d220de
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
