name       : kaccounts-integration
version    : 18.08.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kaccounts-integration-18.08.1.tar.xz : fa6322ceca6c49a8ed75d45f07f93f971a70553c8bc832fcdf1d4ee53791cba2
license    : LGPL-2.1-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
