name       : kaccounts-integration
version    : 22.04.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kaccounts-integration-22.04.3.tar.xz : 1edb9b8984b000f953ea2368c39485e31939b3dc1844dfb3d2a9476e0a15619b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(signond)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - kwallet-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
    - devel :
        - signond-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
