name       : kaccounts-integration
version    : 23.04.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kaccounts-integration-23.04.3.tar.xz : 4cd939f4c852fea00d9b1883ac24f2e1cb03522eaf62e08b7faa8a5c7827c6d6
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(signond)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - kwallet-devel
    - qcoro-qt5-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
    - devel :
        - signond-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
