name       : kaccounts-integration
version    : 20.12.2
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kaccounts-integration-20.12.2.tar.xz : d2cd7db9a66fa60530db93be3de744166b13ba83ffc47f18e85b2a6dae3bfe96
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(signond)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - kwallet-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
    - devel :
        - signond-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
