name       : kaccounts-integration
version    : 19.12.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kaccounts-integration-19.12.2.tar.xz : fefc25a7bfad2bb00462df0797ce18e28ff0a5a536ba465f856bdcfe6c8504d4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
