name       : kaccounts-integration
version    : 19.08.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kaccounts-integration-19.08.2.tar.xz : b422c23eb3eefc3a79c4ccb9360ae6269a86982575e981bb949c0782f1f813ce
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
