name       : kaccounts-integration
version    : 20.08.2
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kaccounts-integration-20.08.2.tar.xz : 6678ee7d394b69a37e6a220a6cba3804f999997da5803da4bab1d8f329ff30fe
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kwallet-devel
    - kwindowsystem-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
