name       : kaccounts-integration
version    : 21.04.1
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kaccounts-integration-21.04.1.tar.xz : bd4ad3e878a33ad7637a28ecb0de558445f07cb8677df679a241bb6a18b096a1
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(signond)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - kwallet-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
    - devel :
        - signond-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
