name       : kaccounts-integration
version    : 20.12.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kaccounts-integration-20.12.0.tar.xz : 5bc0d40fd52a01bf6d80f7d2db54414dc5bcbf693d1c01e8546e1adaf9137f8d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kwallet-devel
    - kwindowsystem-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
