name       : kaccounts-integration
version    : 20.04.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kaccounts-integration-20.04.0.tar.xz : 33497d7c1797a86ebbf79eefa9aaf24572170de488445b16c120ed5764ede87e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : System to administer web accounts - shared library
description: |
    Small system to administer web accounts for the sites and services across the KDE desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Quick)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
rundeps    :
    - signon-kwallet-extension
    - signon-plugin-oauth2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
